import AppKit
import Carbon.HIToolbox
import SwiftUI

struct ClipboardItem: Identifiable, Codable, Equatable {
    enum Kind: String, Codable {
        case text, image, files
    }

    let id: UUID
    var kind: Kind
    var text: String?
    var fileURLs: [URL]?
    /// Nom du fichier PNG dans le dossier de l'historique (images).
    var imageFile: String?
    var date: Date
    var sourceBundleID: String?
    var isPinned = false
}

enum ClipboardFilter: String, CaseIterable, Identifiable {
    case all, text, images, files, pinned

    var id: String { rawValue }

    var label: String {
        switch self {
        case .all: tr("Tout", "All")
        case .text: tr("Texte", "Text")
        case .images: tr("Images", "Images")
        case .files: tr("Fichiers", "Files")
        case .pinned: tr("Épinglés", "Pinned")
        }
    }

    func matches(_ item: ClipboardItem) -> Bool {
        switch self {
        case .all: true
        case .text: item.kind == .text
        case .images: item.kind == .image
        case .files: item.kind == .files
        case .pinned: item.isPinned
        }
    }
}

enum ClipboardShortcut: String, CaseIterable, Identifiable {
    case off, controlCommandV, optionCommandV, shiftCommandV

    var id: String { rawValue }

    var label: String {
        switch self {
        case .off: tr("Aucun", "None")
        case .controlCommandV: "⌃⌘V"
        case .optionCommandV: "⌥⌘V"
        case .shiftCommandV: "⇧⌘V"
        }
    }

    var carbonModifiers: Int? {
        switch self {
        case .off: nil
        case .controlCommandV: cmdKey | controlKey
        case .optionCommandV: cmdKey | optionKey
        case .shiftCommandV: cmdKey | shiftKey
        }
    }
}

@MainActor
@Observable
final class ClipboardModule: IslandModule {
    let id = "clipboard"
    var name: String { tr("Presse-papiers", "Clipboard") }
    let systemImage = "doc.on.clipboard.fill"
    var summary: String {
        tr("Historique de ce que tu copies : clique sur un élément pour le recopier.",
           "History of what you copy: click an item to copy it again.")
    }
    let tint = Color.teal
    let kind = ModuleKind.page

    @ObservationIgnored private let store = ModuleDefaults(moduleID: "clipboard", registering: [
        "maxItems": 40.0,
        "persist": true,
        "ignoreConcealed": true,
        "closeAfterCopy": true,
        "autoPaste": false,
        "shortcut": ClipboardShortcut.controlCommandV.rawValue,
        "fullImages": true,
        "ignoredApps": [String](),
    ])

    var maxItems: Double { didSet { store.set(maxItems, "maxItems"); trim(); save() } }
    var persist: Bool { didSet { store.set(persist, "persist"); save() } }
    /// Ignore ce que les gestionnaires de mots de passe marquent comme confidentiel.
    var ignoreConcealed: Bool { didSet { store.set(ignoreConcealed, "ignoreConcealed") } }
    var closeAfterCopy: Bool { didSet { store.set(closeAfterCopy, "closeAfterCopy") } }
    /// Simule ⌘V dans l'app active après la copie (permission Accessibilité requise).
    var autoPaste: Bool {
        didSet {
            store.set(autoPaste, "autoPaste")
            if autoPaste { requestAccessibility() }
        }
    }
    var shortcut: ClipboardShortcut { didSet { store.set(shortcut.rawValue, "shortcut"); registerShortcut() } }
    /// Images affichées en entier (sinon rognées pour remplir la carte).
    var fullImages: Bool { didSet { store.set(fullImages, "fullImages") } }
    /// Identifiants des apps dont les copies ne sont jamais gardées.
    var ignoredApps: [String] { didSet { store.set(ignoredApps, "ignoredApps") } }

    private(set) var items: [ClipboardItem] = []
    private(set) var shortcutConflict = false
    var filter = ClipboardFilter.all
    var hoveredItem: UUID?
    private(set) var copiedItem: UUID?

    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var lastChangeCount = NSPasteboard.general.changeCount
    @ObservationIgnored private var hotKey: GlobalHotKey?
    @ObservationIgnored private var images: [UUID: NSImage] = [:]
    @ObservationIgnored private var didLoad = false

    private static let directory = URL.applicationSupportDirectory.appending(path: "Island/Clipboard", directoryHint: .isDirectory)
    private static let indexFile = directory.appending(path: "history.json")

    /// Types posés par les gestionnaires de mots de passe (convention nspasteboard.org).
    private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    init() {
        maxItems = store.double("maxItems")
        persist = store.bool("persist")
        ignoreConcealed = store.bool("ignoreConcealed")
        closeAfterCopy = store.bool("closeAfterCopy")
        autoPaste = store.bool("autoPaste")
        shortcut = ClipboardShortcut(rawValue: store.string("shortcut")) ?? .off
        fullImages = store.bool("fullImages")
        ignoredApps = store.strings("ignoredApps")
    }

    var filteredItems: [ClipboardItem] {
        items.filter(filter.matches)
    }

    func expandedView() -> AnyView { AnyView(ClipboardView(module: self)) }
    func settingsView() -> AnyView? { AnyView(ClipboardSettingsView(module: self)) }

    func start() {
        #if DEBUG
        // Historique fictif pour les captures publiques : rien n'est lu ni enregistré sur le disque.
        if CommandLine.arguments.contains("--demo-media") {
            let now = Date.now
            items = [
                ClipboardItem(id: UUID(), kind: .text, text: "Ship the island redesign 🚀", date: now.addingTimeInterval(-40),
                              sourceBundleID: "com.apple.Notes"),
                ClipboardItem(id: UUID(), kind: .text, text: "https://github.com/emmanuellion/macland",
                              date: now.addingTimeInterval(-300), sourceBundleID: "com.apple.Safari", isPinned: true),
                ClipboardItem(id: UUID(), kind: .files, fileURLs: [URL(filePath: "/System/Applications/Music.app")],
                              date: now.addingTimeInterval(-1500), sourceBundleID: "com.apple.finder"),
                ClipboardItem(id: UUID(), kind: .text, text: "#8E7CFF", date: now.addingTimeInterval(-4000),
                              sourceBundleID: "com.apple.TextEdit"),
            ]
            return
        }
        #endif
        if !didLoad {
            didLoad = true
            load()
        }
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        registerShortcut()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        hotKey?.unregister()
        hotKey = nil
    }

    // MARK: Capture

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = pasteboard.types ?? []
        if ignoreConcealed, !Self.concealedTypes.isDisjoint(with: types) { return }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if let source, ignoredApps.contains(source) { return }
        // L'ordre des types reflète la préférence de l'app qui a copié.
        for type in types {
            if type == .fileURL,
               let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
               !urls.isEmpty {
                insert(ClipboardItem(id: UUID(), kind: .files, fileURLs: urls, date: .now, sourceBundleID: source))
                return
            }
            if type == .png || type == .tiff, let data = pasteboard.data(forType: type), let image = NSImage(data: data) {
                insertImage(image, source: source)
                return
            }
            if type == .string, let text = pasteboard.string(forType: .string),
               !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                insert(ClipboardItem(id: UUID(), kind: .text, text: text, date: .now, sourceBundleID: source))
                return
            }
        }
    }

    private func insertImage(_ image: NSImage, source: String?) {
        let id = UUID()
        let fileName = "\(id.uuidString).png"
        guard let tiff = image.tiffRepresentation,
              let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) else { return }
        try? FileManager.default.createDirectory(at: Self.directory, withIntermediateDirectories: true)
        guard (try? png.write(to: Self.directory.appending(path: fileName))) != nil else { return }
        images[id] = image
        insert(ClipboardItem(id: id, kind: .image, imageFile: fileName, date: .now, sourceBundleID: source))
    }

    private func insert(_ item: ClipboardItem) {
        // Même contenu déjà présent : on le remonte au lieu de le dupliquer.
        if let existing = items.firstIndex(where: { $0.kind == item.kind && $0.kind != .image
            && $0.text == item.text && $0.fileURLs == item.fileURLs }) {
            var moved = items.remove(at: existing)
            moved.date = .now
            items.insert(moved, at: 0)
        } else {
            items.insert(item, at: 0)
        }
        trim()
        save()
    }

    private func trim() {
        let limit = Int(maxItems)
        while items.filter({ !$0.isPinned }).count > limit,
              let index = items.lastIndex(where: { !$0.isPinned }) {
            deleteFiles(of: items.remove(at: index))
        }
    }

    // MARK: Actions

    func copy(_ item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch item.kind {
        case .text:
            pasteboard.setString(item.text ?? "", forType: .string)
        case .files:
            pasteboard.writeObjects((item.fileURLs ?? []) as [NSURL])
        case .image:
            if let image = image(for: item) { pasteboard.writeObjects([image]) }
        }
        lastChangeCount = pasteboard.changeCount

        if let index = items.firstIndex(where: { $0.id == item.id }) {
            var moved = items.remove(at: index)
            moved.date = .now
            items.insert(moved, at: 0)
            save()
        }

        copiedItem = item.id
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.8) { [weak self] in
            MainActor.assumeIsolated {
                guard let self, self.copiedItem == item.id else { return }
                self.copiedItem = nil
                if self.closeAfterCopy || self.autoPaste { IslandCommands.collapse() }
                if self.autoPaste { self.pasteInFrontApp() }
            }
        }
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        trim()
        save()
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        deleteFiles(of: item)
        save()
    }

    /// Vide l'historique, en gardant les éléments épinglés.
    func clear() {
        items.filter { !$0.isPinned }.forEach(remove)
    }

    func image(for item: ClipboardItem) -> NSImage? {
        if let cached = images[item.id] { return cached }
        guard let file = item.imageFile, let image = NSImage(contentsOf: Self.directory.appending(path: file)) else { return nil }
        images[item.id] = image
        return image
    }

    // MARK: Apps ignorées

    /// Ouvre un sélecteur d'app à ajouter aux apps ignorées.
    func chooseAppToIgnore() {
        let panel = NSOpenPanel()
        panel.title = tr("Choisir une app à ignorer", "Choose an app to ignore")
        panel.directoryURL = URL(filePath: "/Applications")
        panel.allowedContentTypes = [.application]
        panel.allowsMultipleSelection = true
        NSApp.activate()
        guard panel.runModal() == .OK else { return }
        let ids = panel.urls.compactMap { Bundle(url: $0)?.bundleIdentifier }
        ignoredApps.append(contentsOf: ids.filter { !ignoredApps.contains($0) })
    }

    func stopIgnoring(_ bundleID: String) {
        ignoredApps.removeAll { $0 == bundleID }
    }

    static func appName(_ bundleID: String) -> String {
        guard let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID) else { return bundleID }
        return FileManager.default.displayName(atPath: url.path).replacingOccurrences(of: ".app", with: "")
    }

    // MARK: Raccourci & collage

    private func registerShortcut() {
        hotKey?.unregister()
        hotKey = nil
        shortcutConflict = false
        guard timer != nil, let modifiers = shortcut.carbonModifiers else { return }
        hotKey = GlobalHotKey(keyCode: kVK_ANSI_V, modifiers: modifiers) { [weak self] in
            guard let self else { return }
            IslandCommands.open(page: self.id)
        }
        shortcutConflict = hotKey == nil
    }

    var hasAccessibility: Bool { AXIsProcessTrusted() }

    private func requestAccessibility() {
        let options = ["AXTrustedCheckOptionPrompt": true] as CFDictionary
        _ = AXIsProcessTrustedWithOptions(options)
    }

    private func pasteInFrontApp() {
        guard AXIsProcessTrusted() else { return }
        let source = CGEventSource(stateID: .combinedSessionState)
        let down = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    // MARK: Persistance

    private func deleteFiles(of item: ClipboardItem) {
        images[item.id] = nil
        if let file = item.imageFile {
            try? FileManager.default.removeItem(at: Self.directory.appending(path: file))
        }
    }

    private func save() {
        guard didLoad else { return }
        if persist {
            try? FileManager.default.createDirectory(at: Self.directory, withIntermediateDirectories: true)
            try? JSONEncoder().encode(items).write(to: Self.indexFile)
        } else {
            try? FileManager.default.removeItem(at: Self.indexFile)
        }
    }

    private func load() {
        guard persist,
              let data = try? Data(contentsOf: Self.indexFile),
              let saved = try? JSONDecoder().decode([ClipboardItem].self, from: data)
        else {
            // Sans persistance, les images d'une session précédente ne servent plus.
            try? FileManager.default.removeItem(at: Self.directory)
            return
        }
        items = saved
    }
}

// MARK: - Vue

private struct ClipboardView: View {
    let module: ClipboardModule

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: 4) {
                ForEach(ClipboardFilter.allCases) { filter in
                    Button {
                        module.filter = filter
                    } label: {
                        Text(filter.label)
                            .font(.system(size: 11, weight: .semibold))
                            .foregroundStyle(module.filter == filter ? AnyShapeStyle(.background) : AnyShapeStyle(Color.primary.opacity(0.6)))
                            .padding(.horizontal, 9)
                            .frame(height: 20)
                            .background(Capsule().fill(module.filter == filter ? Color.primary : Color.primary.opacity(0.08)))
                            .contentShape(Capsule())
                    }
                    .buttonStyle(.plain)
                }
                Spacer()
                if !module.items.isEmpty {
                    Button { module.clear() } label: {
                        Image(systemName: "trash")
                            .font(.system(size: 11, weight: .semibold))
                            .foregroundStyle(Color.primary.opacity(0.5))
                            .frame(width: 24, height: 20)
                            .contentShape(Rectangle())
                    }
                    .buttonStyle(.plain)
                    .help(tr("Vider l'historique (les éléments épinglés sont gardés)", "Clear history (pinned items are kept)"))
                }
            }

            let items = module.filteredItems
            if items.isEmpty {
                VStack(spacing: 4) {
                    Image(systemName: "doc.on.clipboard")
                        .font(.system(size: 18))
                    Text(module.items.isEmpty
                         ? tr("Copie quelque chose, il apparaîtra ici", "Copy something and it will show up here")
                         : tr("Rien dans cette catégorie", "Nothing in this category"))
                        .font(.system(size: 11, weight: .medium))
                }
                .foregroundStyle(Color.primary.opacity(0.4))
                .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                ScrollView(.horizontal) {
                    LazyHStack(spacing: 8) {
                        ForEach(items) { item in
                            ClipboardCard(module: module, item: item)
                        }
                    }
                }
                .scrollIndicators(.never)
            }
        }
    }
}

private struct ClipboardCard: View {
    let module: ClipboardModule
    let item: ClipboardItem

    private var isHovered: Bool { module.hoveredItem == item.id }
    private var isCopied: Bool { module.copiedItem == item.id }

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 5) {
                if let bundleID = item.sourceBundleID,
                   let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID) {
                    Image(nsImage: NSWorkspace.shared.icon(forFile: url.path))
                        .resizable()
                        .frame(width: 14, height: 14)
                }
                Text(item.date, format: .relative(presentation: .named, unitsStyle: .abbreviated).locale(IslandSettings.shared.locale))
                    .font(.system(size: 9.5, weight: .medium))
                    .foregroundStyle(Color.primary.opacity(0.45))
                    .lineLimit(1)
                Spacer(minLength: 0)
                if item.isPinned {
                    Image(systemName: "pin.fill")
                        .font(.system(size: 9))
                        .foregroundStyle(.yellow)
                }
            }

            content
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topLeading)
        }
        .padding(8)
        .frame(width: item.kind == .image ? 176 : 138)
        .frame(maxHeight: .infinity)
        .background(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .fill(Color.primary.opacity(isHovered ? 0.13 : 0.07))
        )
        .overlay {
            if isCopied {
                RoundedRectangle(cornerRadius: 12, style: .continuous)
                    .fill(.background.opacity(0.85))
                    .overlay(Label(tr("Copié", "Copied"), systemImage: "checkmark").font(.system(size: 12, weight: .semibold)))
                    .transition(.opacity)
            }
        }
        .overlay(alignment: .topTrailing) {
            if isHovered && !isCopied {
                HStack(spacing: 2) {
                    CardButton(systemImage: item.isPinned ? "pin.slash.fill" : "pin.fill") { module.togglePin(item) }
                    CardButton(systemImage: "xmark") { module.remove(item) }
                }
                .padding(4)
            }
        }
        .contentShape(RoundedRectangle(cornerRadius: 12))
        .onTapGesture { module.copy(item) }
        .onHover { inside in
            if inside { module.hoveredItem = item.id } else if isHovered { module.hoveredItem = nil }
        }
        .animation(.smooth(duration: 0.15), value: isCopied)
    }

    @ViewBuilder private var content: some View {
        switch item.kind {
        case .text:
            Text(item.text ?? "")
                .font(.system(size: 11))
                .foregroundStyle(Color.primary.opacity(0.9))
                .lineLimit(4)
        case .image:
            if let image = module.image(for: item) {
                // L'image remplit la carte sans en déborder (scaledToFill seul agrandit le cadre).
                Color.primary.opacity(0.08)
                    .overlay {
                        if module.fullImages {
                            Image(nsImage: image).resizable().scaledToFit()
                        } else {
                            Image(nsImage: image).resizable().scaledToFill()
                        }
                    }
                    .clipShape(RoundedRectangle(cornerRadius: 6))
            }
        case .files:
            let urls = item.fileURLs ?? []
            HStack(spacing: 6) {
                if let first = urls.first {
                    Image(nsImage: NSWorkspace.shared.icon(forFile: first.path))
                        .resizable()
                        .frame(width: 30, height: 30)
                }
                Text(urls.count > 1 ? tr("\(urls.count) fichiers", "\(urls.count) files") : urls.first?.lastPathComponent ?? "")
                    .font(.system(size: 11, weight: .medium))
                    .foregroundStyle(Color.primary.opacity(0.9))
                    .lineLimit(3)
            }
        }
    }
}

private struct CardButton: View {
    let systemImage: String
    let action: () -> Void

    var body: some View {
        Button(action: action) {
            Image(systemName: systemImage)
                .font(.system(size: 9, weight: .bold))
                .foregroundStyle(.white)
                .frame(width: 20, height: 20)
                .background(Circle().fill(.black.opacity(0.6)))
        }
        .buttonStyle(.plain)
    }
}

// MARK: - Réglages

private struct ClipboardSettingsView: View {
    @Bindable var module: ClipboardModule

    var body: some View {
        PickerRow(tr("Raccourci d'ouverture", "Open shortcut"),
                  subtitle: module.shortcutConflict
                      ? tr("Ce raccourci est déjà utilisé par une autre app.", "This shortcut is already used by another app.")
                      : tr("Ouvre l'historique depuis n'importe où.", "Opens the history from anywhere."),
                  selection: $module.shortcut) {
            ForEach(ClipboardShortcut.allCases) { Text($0.label).tag($0) }
        }
        SliderRow(tr("Taille de l'historique", "History size"),
                  subtitle: tr("Les éléments épinglés ne comptent pas.", "Pinned items don't count."),
                  value: $module.maxItems, range: 10...200, step: 10) { "\(Int($0))" }
        ToggleRow(tr("Conserver après redémarrage", "Keep after restart"), isOn: $module.persist)
        ToggleRow(tr("Ignorer les mots de passe", "Ignore passwords"),
                  subtitle: tr("Ne garde pas ce que les gestionnaires de mots de passe signalent comme confidentiel.",
                               "Doesn't keep what password managers mark as confidential."),
                  isOn: $module.ignoreConcealed)
        ToggleRow(tr("Images entières", "Full images"),
                  subtitle: tr("Sinon, les images sont rognées pour remplir la carte.", "Otherwise, images are cropped to fill the card."),
                  isOn: $module.fullImages)
        ToggleRow(tr("Fermer l'île après une copie", "Close island after copying"), isOn: $module.closeAfterCopy)
        ToggleRow(tr("Coller automatiquement", "Paste automatically"),
                  subtitle: module.autoPaste && !module.hasAccessibility
                      ? tr("Autorise Island dans Confidentialité et sécurité › Accessibilité.",
                           "Allow Island in Privacy & Security › Accessibility.")
                      : tr("Colle directement dans l'app active (permission Accessibilité).",
                           "Pastes straight into the active app (Accessibility permission)."),
                  isOn: $module.autoPaste)
        SettingsRow(tr("Historique", "History"),
                    subtitle: tr("\(module.items.count) élément\(module.items.count > 1 ? "s" : "")",
                                 "\(module.items.count) item\(module.items.count == 1 ? "" : "s")")) {
            Button(tr("Vider", "Clear"), role: .destructive) { module.clear() }
                .disabled(module.items.isEmpty)
        }
        SettingsSubheader(tr("Apps ignorées", "Ignored apps"))
        ForEach(module.ignoredApps, id: \.self) { bundleID in
            SettingsRow(ClipboardModule.appName(bundleID), subtitle: bundleID) {
                Button(tr("Retirer", "Remove")) { module.stopIgnoring(bundleID) }
            }
        }
        SettingsRow(tr("Ajouter une app", "Add an app"),
                    subtitle: tr("Ce que tu copies dans ces apps n'est jamais gardé (ex. : banque, gestionnaire de mots de passe).",
                                 "What you copy in these apps is never kept (e.g. banking, password manager).")) {
            Button(tr("Choisir…", "Choose…")) { module.chooseAppToIgnore() }
        }
    }
}
